# Generated by Django 3.1.4 on 2021-09-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='After',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.EmailField(max_length=30)),
                ('receiver', models.EmailField(max_length=30)),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('bank_id', models.IntegerField(unique=True)),
                ('balance', models.IntegerField()),
                ('email', models.EmailField(max_length=300, unique=True)),
            ],
        ),
    ]
