# Generated by Django 3.1.4 on 2021-08-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transactions',
            new_name='transaction',
        ),
    ]
